services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
    volumes:
      - /home/max/configs/radarr:/config
      - /mnt/hdd:/mnt/hdd
    ports:
      - 7878:7878
    restart: unless-stopped
