services:
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    volumes:
      - kapowarr-db:/app/db
      - /mnt/hdd/torrents/comics:/app/temp_downloads
      - /mnt/hdd/media/comics:/comics
    ports:
      - 5656:5656
      - TZ=Europe/Minsk
    restart: unless-stopped

volumes:
  kapowarr-db:
